[tool.pytest.ini_options]
addopts = "--url=https://jsonplaceholder.typicode.com/ --method=get --status_code=200"
log_cli = "1"
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)4s] %(message)s"
log_format = "%(asctime)s [%(levelname)4s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_date_format = "%H:%M:%S"